### DISCUSSION TITLE
fetch models folder from other drive?

### DISCUSSION THREAD

**Discussion by chnisar515** [comfyanonymous/ComfyUI#5015] [General]
Hello Experts,

I am currently facing storage constraints on my primary 1TB SSD, which is nearly full. To free up space, I’ve decided to move my Models folder for ComfyUI to my second hard drive located in the E:\ drive. I do not have any other web UI tools like A1111 installed on this drive.

Here’s what I’ve done so far:
I copied the ComfyUI Models folder from its original location on the SSD to the following path: E:\My AI\comfyui\models. Then, from the ComfyUI portable directory (C:\ComfyUI_windows_portable\ComfyUI\models), I opened Command Prompt and ran the following command:

`mklink /D models "E:\My AI\comfyui\models"`

This created a symbolic link for the models folder within the ComfyUI directory. Afterward, I started ComfyUI and verified that all the data from my Models folder is correctly displayed.

My question is:
Will this method work consistently in all scenarios, or are there any potential issues or limitations I should be aware of?

**Comment by Woisek** [comment]
Junctions are the way to go. The only thing I would change, is, to remove spaces in path and file names. Saves a lot of headaches in some cases,

**Comment by ltdrdata** [comment]
If you do it that way, problems will occur when updating ComfyUI.
Instead, copy `ComfyUI/extra_model_paths.yaml.example` to `ComfyUI/extra_model_paths.yaml` and modify it for use.

**Reply by chnisar515** [reply]
> If you do it that way, problems will occur when updating ComfyUI. Instead, copy `ComfyUI/extra_model_paths.yaml.example` to `ComfyUI/extra_model_paths.yaml` and modify it for use.

Thank you for your reply, as i already gave you my new path of models folder so can you guide me how i can update it in `ComfyUI/extra_model_paths.yaml` ? i not a developer so please guide me.

**Reply by stoutimon** [reply]
thanks for the quick response dude. I'm trying to direct models from comfy pinokio to comfy local, will this work?

**Comment by ltdrdata** [comment]
```
comfyui:
     base_path: E:\My AI\comfyui\models
     is_default: true
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     diffusion_models: |
                  models/diffusion_models
                  models/unet
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
```

But I recommend that you remove the blanks in the path as mentioned above.
Blanks in paths often cause trouble.
