### ISSUE TITLE
Support for ControlNet models with custom configuration files

### ISSUE THREAD

**Issue by jamesWalker55** [comfyanonymous/ComfyUI#1131]
Some ControlNet models like [TemporalNet2](https://huggingface.co/CiaraRowles/TemporalNet2) have custom configurations than typical models, in the config for TemporalNet2:

```yaml
    control_stage_config:
      target: cldm.cldm.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 6
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
```

It uses 6 channels for the hint channel instad of 3. When attempting to load this in ComfyUI, it gives this error:

```
RuntimeError: Error(s) in loading state_dict for WeightsLoader:
        size mismatch for control_model.input_hint_block.0.weight: copying a param with shape torch.Size([16, 6, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3]).
```

It seems that ComfyUI is failing to detect the configuration, and trying to load 3 hint channels instead.
