### ISSUE TITLE
--extra-model-paths-config finds folders but not models inside them

### ISSUE THREAD

**Issue by 404exchange** [comfyanonymous/ComfyUI#2389]
When starting comfyui with the argument `--extra-model-paths-config ./models1-5.yaml`, ComfyUI does recognize it and declare it is searching these folders for extra models on startup. 
```
Adding extra search path checkpoints ~/Projects/Models/models1-5/checkpoints/
Adding extra search path loras ~/Projects/Models/models1-5/loras/
Adding extra search path vae ~/Projects/Models/models1-5/vae/
```
However, it is does not find any models, despite them being present. 
```
ls  ~/Projects/Models/models1-5/checkpoints/
envypoodamix_v10.safetensors
clarity_3.safetensors
```
Contents of ~/Projects/ComfyUI/models1-5.yaml
```
comfyui:
     base_path: ~/Projects/Models/
     checkpoints: models1-5/checkpoints/
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     configs: models/configs/
#     controlnet: models/controlnet/
#     embeddings: models/embeddings/
     loras: models1-5/loras/
#     upscale_models: models/upscale_models/
     vae: models1-5/vae/
```

I've tried moving the models out of the ComfyUI folder to see if that mattered, and it had no change. 

Am I missing something, or is this not working as intended? I've tried to figure this out for about an hour, and it appears that ComfyUI is receiving the .yaml file correctly, and just not seeing the checkpoints / models in them. I have also tried changing line 1 of models1-5.yaml to `A1111` or `other_ui`, in case it changed the behavior. These models worked fine for me until now; I was trying to seperate out my SDXL and SD1.5 models and pass ComfyUI a different argument based on which I was wanting to use.
