### ISSUE TITLE
Content of extra_model_paths.yaml  overriden by init_custom_nodes()

### ISSUE THREAD

**Issue by thjan** [comfyanonymous/ComfyUI#2630]
Hi, 
 I am trying to set a share models folder on my network to avoid storing them all in the ComfyUI root folder. I am using the `extra_model_paths.yaml` file which works great except for a few custom nodes. It seems that a bunch of custom nodes override the extra folders paths doing the following at loading: 
 ```
dir_facerestore_models = os.path.join(folder_paths.models_dir, "facerestore_models")
dir_facedetection_models = os.path.join(folder_paths.models_dir, "facedetection")
os.makedirs(dir_facerestore_models, exist_ok=True)
os.makedirs(dir_facedetection_models, exist_ok=True)
folder_paths.folder_names_and_paths["facerestore_models"] = (
    [dir_facerestore_models],
    folder_paths.supported_pt_extensions,
)
folder_paths.folder_names_and_paths["facedetection_models"] = (
    [dir_facedetection_models],
    folder_paths.supported_pt_extensions,
)

```

This is from the (facerestore)[https://github.com/mav-rik/facerestore_cf/tree/master] node, and I would consider it an issue of the node's repo but it seems to be happening with a bunch of other custom nodes as well, maybe a common practice in custom node development ? I looked a bit at the loading logic and swapping the custom nodes init and extra paths processing won't work since extra paths can contain paths for custom_nodes. 
Is there an option/feature/mechanism/wizardry to allow storing all the models in custom locations  somewhere in the repo ? 

Thank you ! 

For reference, here is a truncated output of `folder_paths.folder_names_and_paths` before and after the call to `init_custom_nodes`.

Before the `init_custom_nodes` call in `main.py`
```
{
  ...
  "photomaker": [
    [
      "/home/thjan/repos/ComfyUI/models/photomaker"
    ],
  ],
  "classifiers": [
    [
      "/home/thjan/repos/ComfyUI/models/classifiers"
    ],
  ],
  "facerestore_models": [
    [
      "/home/thjan/repos/shared-models/models/facerestore_models"
    ],
  ],
  "ipadapter": [
    [
      "/home/thjan/repos/shared-models/models/ipadapter"
    ],
  ],
  "facedetection": [
    [
      "/home/thjan/repos/shared-models/models/facedetection"
    ],
  ],
  "face_restore": [
    [
      "/home/thjan/repos/shared-models/models/face_restore"
    ],
  ],
  "sams": [
    [
      "/home/thjan/repos/shared-models/models/sams"
    ],
  ]
}
```

After the `init_custom_nodes` call in `main.py`:
```
{
  ...
  "photomaker": [
    [
      "/home/thjan/repos/ComfyUI/models/photomaker"
    ],
  ],
  "classifiers": [
    [
      "/home/thjan/repos/ComfyUI/models/classifiers"
    ],
  ],
  "facerestore_models": [
    [
      "/home/thjan/repos/ComfyUI/models/facerestore_models"
    ],

  ],
  "ipadapter": [
    [
      "/home/thjan/repos/shared-models/models/ipadapter"
    ],

  ],
  "facedetection": [
    [
      "/home/thjan/repos/shared-models/models/facedetection"
    ],
  ],
  "face_restore": [
    [
      "/home/thjan/repos/shared-models/models/face_restore"
    ],
  ],
  "sams": [
    [
      "/home/thjan/repos/ComfyUI/models/sams"
    ],

  ],
  "blip": [
    [
      "/home/thjan/repos/ComfyUI/models/blip"
    ],

  ],
  "isnet": [
    [
      "/home/thjan/repos/ComfyUI/models/isnet"
    ],

  ],
  "facedetection_models": [
    [
      "/home/thjan/repos/ComfyUI/models/facedetection"
    ],
  ]
}
```

I removed a big chunk of the output in an effort to make it more concise, but we can see here that paths are changed (or added) by a bunch of custom_nodes. As a reference, here is my `extra_model_paths.yaml`:
```
comfyui: 
  base_path: /home/thjan/repos/shared-models
  checkpoints: checkpoints 
  configs: configs 
  embeddings: embeddings 
  facerestore_models: facerestore_models 
  ipadapter: ipadapter 
  unet: unet 
  vae_approx: vae_approx 
  clip: clip 
  controlnet: controlnet 
  facedetection: facedetection 
  gligen: gligen 
  loras: loras 
  upscale_models: upscale_models 
  clip_vision: clip_vision 
  diffusers: diffusers 
  face_restore: face_restore 
  hypernetworks: hypernetworks 
  style_models: style_models 
  vae: vae
  sams: sams
```
I am using: 
```
ComfyUI: 1930[d1533d](2024-01-24)
Manager: V2.2.5
```
