### ISSUE TITLE
Extra model path found but 'Load Checkpoint' widget not populated!

### ISSUE THREAD

**Issue by Fredrum** [comfyanonymous/ComfyUI#2910]
Hi I'm finally getting around to start playing with Comfy! :) I have been wanting to for a while!
I'm trying to point to mu A1111 models folder structure and it seems my Windows install of ComfyUI finds it as it tells me so in the startup shell,

```
Adding extra search path checkpoints D:\ai\a1111\models/Stable-diffusion
Adding extra search path configs D:\ai\a1111\models/Stable-diffusion
Adding extra search path vae D:\ai\a1111\models/VAE
Adding extra search path loras D:\ai\a1111\models/Lora
Adding extra search path loras D:\ai\a1111\models/LyCORIS
Adding extra search path upscale_models D:\ai\a1111\models/ESRGAN
Adding extra search path upscale_models D:\ai\a1111\models/RealESRGAN
Adding extra search path upscale_models D:\ai\a1111\models/SwinIR
Adding extra search path embeddings D:\ai\a1111\embeddings
Adding extra search path hypernetworks D:\ai\a1111\models/hypernetworks
Adding extra search path controlnet D:\ai\a1111\models/ControlNet
Starting server
```

But inside Comfy gui and the default network that's there on start the 'Load Checkpoint' widget popup menu does not get populated by the contents of the A1111 folder. 
I copied one of them over to the comfy checkpoints folder and refreshed and it was found.

So something seems not to work.

My extra model file looks like:

```
#Rename this to extra_model_paths.yaml and ComfyUI will load it


#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: D:\ai\a1111

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

#comfyui:
#     base_path: path/to/comfyui/
#     checkpoints: models/checkpoints/
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     configs: models/configs/
#     controlnet: models/controlnet/
#     embeddings: models/embeddings/
#     loras: models/loras/
#     upscale_models: models/upscale_models/
#     vae: models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
```
