### ISSUE TITLE
Can I have Multiple PATHS for checkpoints?

### ISSUE THREAD

**Issue by GithubStable** [comfyanonymous/ComfyUI#2915]
I opened the yaml file and I see a path for the base "path" of a1111, ok but what if I want to add multiple checkpoints folders paths as I ahev them in multiple locations? 
How?

**Comment by ashllay** [comment]
rename extra_model_paths.yaml.example to extra_model_paths.yaml and edit with your custom paths. 
here mine as a example.
`#Rename this to extra_model_paths.yaml and ComfyUI will load it

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: D:/diffusion/stable-diffusion-webui/

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet

other_ui:
    base_path: G:/Diffusion/stable-diffusion-webui-forge/
    checkpoints: models/Stable-diffusion/
    clip: models/clip/
    clip_vision: models/clip_vision/
    configs: models/Stable-diffusion/
    controlnet: models/controlnet/
    embeddings: models/embeddings/
    loras: models/lora/
    upscale_models: models/upscale_models/
    vae: models/vae/
    ipdapter: models/ipdapter/

comfyui:
     base_path: path/to/comfyui/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
     ipdapter: models/ipdapter/`

**Comment by GithubStable** [comment]
Isaw your otherUi part, can I have multiple of those? (lets sayu I have 5 paths)

**Comment by titidatiti** [comment]
You can use | in the extra_model_paths.yaml to add extra paths.

`comfyui:
     base_path: /home/runner/ComfyUI/
     checkpoints: |
                  models/checkpoints/
                  YOUR_PATH/checkpoints/
`

**Comment by ltdrdata** [comment]
You can enumerate multiple models.

```
electron:
   base_path: /mnt/teratera/test_path1
   download_model_base: models
   checkpoints: models/checkpoints
   text_encoders: models/text_encoders
   vae: models/vae
   loras: models/loras
   controlnet: models/controlnet
   clip_vision: models/clip_vision
   gligen: models/gligen
   upscale_models: models/upscale_models
   embeddings: models/embeddings
   diffusion_models: models/diffusion_models
   custom_nodes: custom_nodes
   is_default: True
   ultralytics_bbox: models/ultralytics/bbox

other_ui2:
   base_path: /mnt/teratera/test_path2
   custom_nodes: custom_nodes
   inspire_prompts: inspire_prompts
   checkpoints: models/checkpoints
```
