### ISSUE TITLE
Sharing custom_nodes, clip_vision and other models folders

### ISSUE THREAD

**Issue by nothingness6** [comfyanonymous/ComfyUI#3143]
I'm using 2 ComfyUIs. One with Stability Matrix and another one with just portable version. I could manage the models that are used in Automatic1111, and they work fine, which means, #config for a1111 ui, works fine. 
But the ComfyUI models such as custom_nodes, clip_vision and other models (eg:  animatediff_models, facerestore_models, insightface and sams) are not sharable, which means, #config for comfyui, seems not working. 
I modified the extra_model_paths.yaml file as below:
```
#Rename this to extra_model_paths.yaml and ComfyUI will load it


#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/ControlNet

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

#comfyui:
#     base_path: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI
#     checkpoints: models/checkpoints/
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     configs: models/configs/
#     controlnet: models/controlnet/
#     embeddings: models/embeddings/
#     loras: models/loras/
#     upscale_models: models/upscale_models/
#     vae: models/vae/
#     animatediff_motion_lora: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\animatediff_motion_lora\
#     animatediff_models: M:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\animatediff_models\

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
```
But it doesn't work as I thought. 
How do I make them sharable?
