### ISSUE TITLE
Unofficial ComfyUI docker image

### ISSUE THREAD

**Issue by sinfallas** [comfyanonymous/ComfyUI#6729]
Hello, I would like to show you my small contribution so that you can test it. It is a docker image that you can get at the following address:

https://hub.docker.com/r/sinfallas/comfyui

and the source code of that image can be found in this repository:

https://github.com/sinfallas/comfy-ui-docker/

I hope it is useful to you.

**Comment by kds69** [comment]
hi, thanks for that.
can we store custom nodes and models in a separate volume?

**Comment by abelroes** [comment]
> hi, thanks for that. can we store custom nodes and models in a separate volume?

@kds69 

On their github there's a [docker-compose.yml](https://github.com/sinfallas/comfy-ui-docker/blob/main/docker-compose.yml) as an example.
Mine ended looking like this (for NVIDIA) - I'm still learning how to use it, though:

```yml
services:
  comfy-ui:
    image: sinfallas/comfyui:0.3.18-nvidia
    container_name: comfy-ui
    runtime: nvidia
    ulimits:
      memlock: -1
    environment:
      - PUID=1000
      - PGID=1000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8188:8188
    volumes:
      - /var/lib/docker/volumes/comfy-ui/_data/checkpoints:/app/models/checkpoints
      - /var/lib/docker/volumes/comfy-ui/_data/clip:/app/models/clip
      - /var/lib/docker/volumes/comfy-ui/_data/clip_vision:/app/models/clip_vision
      - /var/lib/docker/volumes/comfy-ui/_data/configs:/app/models/configs
      - /var/lib/docker/volumes/comfy-ui/_data/controlnet:/app/models/controlnet
      - /var/lib/docker/volumes/comfy-ui/_data/diffusers:/app/models/diffusers
      - /var/lib/docker/volumes/comfy-ui/_data/diffusion_models:/app/models/diffusion_models
      - /var/lib/docker/volumes/comfy-ui/_data/embeddings:/app/models/embeddings
      - /var/lib/docker/volumes/comfy-ui/_data/gligen:/app/models/gligen
      - /var/lib/docker/volumes/comfy-ui/_data/hypernetworks:/app/models/hypernetworks
      - /var/lib/docker/volumes/comfy-ui/_data/loras:/app/models/loras
      - /var/lib/docker/volumes/comfy-ui/_data/photomaker:/app/models/photomaker
      - /var/lib/docker/volumes/comfy-ui/_data/style_models:/app/models/style_models
      - /var/lib/docker/volumes/comfy-ui/_data/text_encoders:/app/models/text_encoders
      - /var/lib/docker/volumes/comfy-ui/_data/unet:/app/models/unet
      - /var/lib/docker/volumes/comfy-ui/_data/upscale_models:/app/models/upscale_models
      - /var/lib/docker/volumes/comfy-ui/_data/vae:/app/models/vae
      - /var/lib/docker/volumes/comfy-ui/_data/vae_approx:/app/models/vae_approx
      - /var/lib/docker/volumes/comfy-ui/_data/output:/app/output
      - /var/lib/docker/volumes/comfy-ui/_data/custom_nodes:/app/custom_nodes
    restart: unless-stopped

```
