### ISSUE TITLE
Mapping for additional input dir through extra_models_path.yaml or args

### ISSUE THREAD

**Issue by ashish-aesthisia** [comfyanonymous/ComfyUI#7334]
### Feature Idea

`extra_model_paths.yaml` has been pretty useful in terms of mapping models & custom nodes from two different directories. 

It works for models & custom nodes, but building it in more generic way to accept include all paths such as `input`. 

Here is the overall idea: 

in extra_model_paths.yaml

```
other_ui:
    base_path: /home/ubuntu/
    input: additional_inputs
    custom_nodes: additional_custom_nodes
#    checkpoints: models/checkpoints
#    gligen: models/gligen
```
    
Let me know your thoughts & if you are open for a PR. 

### Existing Solutions

None, tried ` --input-directory` but it changes default to input dir to specified dir. I would like to load inputs from two different dirs, default input path & an additional input path.
