### ISSUE TITLE
Controlling temp dir mem thrash

### ISSUE THREAD

**Issue by hackedpassword** [comfyanonymous/ComfyUI#7865]
### Your question

Hi! My goal is to move temp/ thrash off of C: (win10, pci-e NVME, non-portable ComfyUI install) onto another asset drive (seen as Z:), to gain lots of pagefile vmem (V:) and save C: from being blasted with write hits.

tl;dr When steps are being iterated/rendered, does the user have any control over vmem destination or is that OS managed via pagefile only?

Thus far I have not succeeded in redirecting vmem, can't figure out how to tell ComfyUI where to land vmem thrash. The config var structure is not helping much either, I'll explain. My python'ing is limited, in tracing out what config vars specifically apply to what via code I get lost in inferences. Here's what I have and know so far, inclusive of attempts.

%APPDATA%\ComfyUI\extra_models_config.yaml:
```
comfyui_desktop:
  is_default: "true"
  custom_nodes: custom_nodes/
  download_model_base: models
# this is where comfyui assets live, and if allowed the install but it's not so the install lives in %APPDATA%
# BUT base_path is not the same as config.json: basePath ..?
  base_path: Z:\ComfyUI
# main.py line 242, 253; looks like [temp] is the correct arg ,,?
# cli_args.py line 48 --temp-directory when called as an arg by main.py
  temp: V:\
  temp-directory: V:\temp-directory
  temp_directory: V:\temp_directory
  temp_path: V:\temp_path
# or wait this looks like the right var ..?
  temp_dir: V:\temp_dir
desktop_extensions:
# k custom_nodes must live in %APPDATA% or ComfyUI gets really huffy and pouts
  custom_nodes: C:\Users\[user]\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
```
I wanted the entire install off of C:, but the .exe installer was stubborn, fine just put assets where I want, that's allowed ok. The above is super confusing because there's another basePath var in config.json, two `custom_nodes`!, one var has a slash where another does not while mixing slashes, no commenting on what controls what, and two custom_nodes that function independently somehow, as in custom_nodes under base_path apparently supercedes custom_nodes under desktop_extension? This was a night of dissimination fyi. As you see I tried various temp dirs as I also worked through the code eventually finding `--temp-directory` can be arg'd to main.py, but how is that called from ComfyUI.exe...? Lots of unanswered questions. :) I even tried hardcoding `--temp-directory` in main.py just to force the usage - no effect on vmem, what the Hoek does `temp_dir` even do?

base_path == asset_path :p

I believe `temp_dir` above is the correct var - but when render passes begin, all vmem ops still go to C: probably to pagefile.sys? My windows env %TEMP% vars point to a RAMdisk (which is dynamic and unused/empty at time of render) so it's not a %TEMP% mis-direction. I added (punted) `temp_directory` to config.json attempting to trigger the main.py arg:
```
{
	"installState": "installed",
	"detectedGpu": "nvidia",
	"basePath": "Z:\\ComfyUI",
	"temp_directory": "V:\\temp-configjson",
	"versionConsentedMetrics": "0.4.32",
	"selectedDevice": "nvidia",
	"hasGeneratedSuccessfully": true
}
```

Slight sidetrack: I have to ask, why are there ~same-name vars in duplicate and/or multiple configs driving ComfyUI's config params? This is crazy confusing and likely somehow makes software developer sense, which I am not. :D What frustrates me more as a user is *why aren't all config vars*, especially critical `base_path` and asset dirs vars, laid out for simple modification within the *Comfy*UI settings? That one I can justify as a UX issue.

Pagefile vs temp: I have an issue I'm fixing on the local side here, Windows10 won't build a pagefile on this V: drive due to some buggy compatibility error being a USB3->NVME/enclosure device disallowing a pagefile there, politely automatically creating a temporary pagefile on C: instead, with notice at startup; this is my problem and I'm working to resolve that. However, I still don't have control of where ComfyUI sends vmem ops to, or, I don't understand exactly how to control how ComfyUI delegates vmem, which includes not recognizing there is no app-level control and vmem is being handled solely by the OS. But wouldn't/couldn't that be a controllable malloc()-ish mem designation?

Maybe switching to the portable install is the practical answer? I'm trying to stay "comfy" with the app exe, in fact I'd very much like to factor python right out and remain focused strictly on the UI. For now, I'm backing off renders til I get that pagefile issue worked out and understand ComfyUI's temp dir usage better.

Thank you for any assistance to better understand the issue!

### Logs

```powershell

```

### Other

Disk names in this image don't align with the above due to some shuffling later, but you get the picture. Disk10 is assets, 9 is the desired pagefile drive, while C: will be smashed with writes for the next hour or two.

![Image](https://github.com/user-attachments/assets/942af9e6-365b-4ea0-8f95-93c45a938d73)
