### ISSUE TITLE
Load models from mounted AWS S3 bucket

### ISSUE THREAD

**Issue by GiuseppeGarone** [comfyanonymous/ComfyUI#8589]
Hi,

I've uploaded my models on a AWS S3 bucket, then I've mounted it as drive on my cloud instance.
The absolute models' paths (from the mounted volume) look like this:

```
/home/ec2-user/mnt/models/checkpoints/...
/home/ec2-user/mnt/models/loras/...
...
```

I've also updated the extra_model_paths.yaml file:

```
comfyui:
  base_path: /home/ec2-user/mnt
  checkpoints: models/checkpoints/
  loras: models/loras/
  ...
```

When I start ComfyUI, I can see from the logs that the extra models paths are correctly added:

```
Adding extra search path checkpoints /home/ec2-user/mnt/models/checkpoints
Adding extra search path loras /home/ec2-user/mnt/models/loras
...
```

However, when I try to run a workflow, I get this error message (model not found):

```
FileNotFoundError: Model in folder 'checkpoints' with filename 'v1-5-pruned-emaonly-fp16.safetensors' not found.
```

Am I missing something about the configuration?
Has someone successfully done something like this?

Thanks.
